<?php

use Illuminate\Database\Seeder;

class ContentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
        	['content' => '','page_id' => '1'],
        	['content' => '','page_id' => '2'],
        	['content' => '','page_id' => '3'],
        	['content' => '','page_id' => '4'],
        	['content' => '','page_id' => '5'],
        	['content' => '','page_id' => '6'],
        	['content' => '','page_id' => '7'],
        	['content' => '','page_id' => '8'],
        	['content' => '','page_id' => '9'],
        	['content' => '','page_id' => '10'],
        	['content' => '','page_id' => '11'],
        	['content' => '','page_id' => '12'],
        	['content' => '','page_id' => '13'],
        	['content' => '','page_id' => '14'],
        	['content' => '','page_id' => '15'],
        	['content' => '','page_id' => '16'],
        	['content' => '','page_id' => '17'],
        	['content' => '','page_id' => '18'],
        	['content' => '','page_id' => '19'],
        	['content' => '','page_id' => '20'],
        	['content' => '','page_id' => '21'],
        	['content' => '','page_id' => '22'],
        	['content' => '','page_id' => '23'],
        	['content' => '','page_id' => '24'],
        	['content' => '','page_id' => '25'],
        	['content' => '','page_id' => '26'],
        	['content' => '','page_id' => '27'],
        	['content' => '','page_id' => '28'],
        	['content' => '','page_id' => '29'],
        	['content' => '','page_id' => '30'],
        	['content' => '','page_id' => '31'],
        	['content' => '','page_id' => '32'],
        	['content' => '','page_id' => '33'],
        	['content' => '','page_id' => '34'],
        	['content' => '','page_id' => '35'],
        	['content' => '','page_id' => '36'],
        	['content' => '','page_id' => '37'],
        	['content' => '','page_id' => '38'],
        	['content' => '','page_id' => '39'],
        	['content' => '','page_id' => '40'],
        	['content' => '','page_id' => '41'],
        	['content' => '','page_id' => '42'],
        	['content' => '','page_id' => '43'],
        	['content' => '','page_id' => '44'],
        	['content' => '','page_id' => '45'],
        	['content' => '','page_id' => '46'],
        	['content' => '','page_id' => '47'],
        	['content' => '','page_id' => '48'],
        	['content' => '','page_id' => '49'],
        	['content' => '','page_id' => '50'],
        	['content' => '','page_id' => '51'],
        	['content' => '','page_id' => '52'],
        	['content' => '','page_id' => '53'],
        	['content' => '','page_id' => '54'],
        	['content' => '','page_id' => '55'],
        	['content' => '','page_id' => '56'],
        	['content' => '','page_id' => '57'],
        	['content' => '','page_id' => '58'],
        	['content' => '','page_id' => '59'],
        	['content' => '','page_id' => '60'],
        	['content' => '','page_id' => '61'],
        	['content' => '','page_id' => '62'],
        	['content' => '','page_id' => '63'],
        	['content' => '','page_id' => '64'],
        	['content' => '','page_id' => '65'],
        	['content' => '','page_id' => '66'],
        	['content' => '','page_id' => '67'],
        	['content' => '','page_id' => '68'],
        	['content' => '','page_id' => '69'],
        	['content' => '','page_id' => '70'],
        	['content' => '','page_id' => '71'],
        	['content' => '','page_id' => '72'],
        	['content' => '','page_id' => '73'],
        	['content' => '','page_id' => '74'],
        	['content' => '','page_id' => '75'],
        	['content' => '','page_id' => '76'],
        	['content' => '','page_id' => '77'],
        	['content' => '','page_id' => '78'],
        	['content' => '','page_id' => '79'],
        	['content' => '','page_id' => '80'],
        	['content' => '','page_id' => '81'],
        	['content' => '','page_id' => '82'],
        	['content' => '','page_id' => '83'],
        	['content' => '','page_id' => '84'],
        	['content' => '','page_id' => '85'],
        	['content' => '','page_id' => '86'],
        	['content' => '','page_id' => '87'],
        	['content' => '','page_id' => '88'],
        	['content' => '','page_id' => '89'],
        	['content' => '','page_id' => '90'],
        	['content' => '','page_id' => '91'],
        	['content' => '','page_id' => '92'],
        	['content' => '','page_id' => '93'],
        	['content' => '','page_id' => '94'],
        	['content' => '','page_id' => '95'],
        	['content' => '','page_id' => '96'],
        	['content' => '','page_id' => '97'],
        	['content' => '','page_id' => '98'],
        	['content' => '','page_id' => '99'],
        	['content' => '','page_id' => '100']
        	);
        DB::table('categories')->insert(
        	$data
        );
    }
}
