<?php

use Illuminate\Database\Seeder;

class PageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {	$data = array(
    		['name' => 'BPL Families','subcategory_id' => 1],
        	['name' => 'General Residents','subcategory_id' => 1],
        	['name' => 'Bulk Residents/Colony','subcategory_id' => 1],
        	['name' => 'Residents and Commercials Combined','subcategory_id' => 1],
        	['name' => 'FAQs','subcategory_id' => 1],
        	['name' => 'Service Request','subcategory_id' => 1],
        	['name' => 'Apply For New Connection','subcategory_id' => 2],
        	['name' => 'Managing your Connection','subcategory_id' => 2],
        	['name' => 'Close your connection','subcategory_id' => 2],
        	['name' => 'Safe Custody','subcategory_id' => 2],
        	['name' => 'Change in Name and Address','subcategory_id' => 2],
        	['name' => 'Change in ownership','subcategory_id' => 2],
        	['name' => 'Change in Load/Demand','subcategory_id' => 2],
        	['name' => 'Change in Category','subcategory_id' => 2],
        	['name' => 'Fees and Security Deposite','subcategory_id' => 2],
        	['name' => 'Know Tariff','subcategory_id' => 2],
        	['name' => 'FAQs','subcategory_id' => 2],
        	['name' => 'Service Request','subcategory_id' => 2],
        	['name' => 'Test Your Meter','subcategory_id' => 3],
        	['name' => 'Purchase/Replace Meter','subcategory_id' => 3],
        	['name' => 'Shift Meter','subcategory_id' => 3],
        	['name' => 'Report stolen Meter','subcategory_id' => 3],
        	['name' => 'Report Defect/Damage Meter','subcategory_id' => 3],
        	['name' => 'Know your Meter','subcategory_id' => 3],
        	['name' => 'FAQs','subcategory_id' => 3],
        	['name' => 'Service Request','subcategory_id' => 3],
        	['name' => 'My Reading Date','subcategory_id' => 4],
        	['name' => 'My Consumption Pattern','subcategory_id' => 4],
        	['name' => 'Report your Reading(Incase not Read)','subcategory_id' => 4],
        	['name' => 'Get a copy downloaded data from meter','subcategory_id' => 4],
        	['name' => 'Report a wrong Reading','subcategory_id' => 4],
        	['name' => 'FAQs','subcategory_id' => 4],
        	['name' => 'Service Request','subcategory_id' => 4],
        	['name' => 'Report non Billing','subcategory_id' => 5],
        	['name' => 'Request Bill correction','subcategory_id' => 5],
        	['name' => 'Request Duplicate bill','subcategory_id' => 5],
        	['name' => 'Know your Bill Parameters','subcategory_id' => 5],
        	['name' => 'Understanding your bill','subcategory_id' => 5],
        	['name' => 'FAQs','subcategory_id' => 5],
        	['name' => 'Service Request','subcategory_id' => 5],
        	['name' => 'Pay bill Online','subcategory_id' => 6],
        	['name' => 'Modes of Payments','subcategory_id' => 6],
        	['name' => 'Payment Plans','subcategory_id' => 6],
        	['name' => 'Nearest Collection Cluster','subcategory_id' => 6],
        	['name' => 'Duplicate Money Receipt','subcategory_id' => 6],
        	['name' => 'Consequences of Non-Payments','subcategory_id' => 6],
        	['name' => 'FAQs','subcategory_id' => 6],
        	['name' => 'Service Request','subcategory_id' => 6],
        	['name' => 'No to Power Theft','subcategory_id' => 7],
        	['name' => 'Not to interfer with Power Installation','subcategory_id' => 7],
        	['name' => 'Inspection of Premises','subcategory_id' => 7],
        	['name' => 'FAQs','subcategory_id' => 7],
        	['name' => 'Service Request','subcategory_id' => 7],
        	['name' => 'Dos and Dont','subcategory_id' => 8],
        	['name' => 'Employees safety Practices','subcategory_id' => 8],
        	['name' => 'Get your Installation Certified','subcategory_id' => 8],
        	['name' => 'Invite us for testing','subcategory_id' => 8],
        	['name' => 'Grid Safety Practices','subcategory_id' => 8],
        	['name' => 'Our People at Work','subcategory_id' => 8],
        	['name' => 'FAQs','subcategory_id' => 8],
        	['name' => 'Service Request','subcategory_id' => 8],
        	['name' => 'Free Energy Audit','subcategory_id' => 9],
        	['name' => 'Plan your Device','subcategory_id' => 9],
        	['name' => 'Energy Efficiency','subcategory_id' => 9],
        	['name' => 'Plan your Consumption','subcategory_id' => 9],
        	['name' => 'Reduce power wastage','subcategory_id' => 9],
        	['name' => 'High Efficiency Equipment','subcategory_id' => 9],
        	['name' => 'Avoid Power factor penality','subcategory_id' => 9],
        	['name' => 'Own your capacity Bank','subcategory_id' => 9],
        	['name' => 'FAQs','subcategory_id' => 9],
        	['name' => 'Service Request','subcategory_id' => 9],
        	['name' => 'Register Yourself','subcategory_id' => 10],
        	['name' => 'FAQs','subcategory_id' => 10],
        	['name' => 'Raise a Service Request','subcategory_id' => 10],
        	['name' => 'Report outage','subcategory_id' => 10],
        	['name' => 'Report power theft/malpractice','subcategory_id' => 10],
        	['name' => 'Request for training','subcategory_id' => 10],
        	['name' => 'Load Calculator','subcategory_id' => 10],
        	['name' => 'Download Forms','subcategory_id' => 10],
        	['name' => 'Your Rights & Responsibilities','subcategory_id' => 10],
        	['name' => 'Feedback','subcategory_id' => 10],
        	['name' => 'Contact Us','subcategory_id' => 10],
        	['name' => 'Supply','subcategory_id' => 11],
        	['name' => 'Connection','subcategory_id' => 11],
        	['name' => 'Meter','subcategory_id' => 11],
        	['name' => 'Reading','subcategory_id' => 11],
        	['name' => 'Bill','subcategory_id' => 11],
        	['name' => 'Payment','subcategory_id' => 11],
        	['name' => 'Messages','subcategory_id' => 11],
        	['name' => 'Service Request','subcategory_id' => 11],
        	['name' => 'Compliances','subcategory_id' => 11],
        	['name' => 'Document Vault/Locker','subcategory_id' => 11],

        	['name' => 'BPL Families','subcategory_id' => 12],
        	['name' => 'General Residents','subcategory_id' => 12],
        	['name' => 'Bulk Residents/Colony','subcategory_id' => 12],
        	['name' => 'Residents and Commercials Combined','subcategory_id' => 12],
        	['name' => 'FAQs','subcategory_id' => 12],
        	['name' => 'Service Request','subcategory_id' => 12],
        	['name' => 'Apply For New Connection','subcategory_id' => 13],
        	['name' => 'Managing your Connection','subcategory_id' => 13],
        	['name' => 'Close your connection','subcategory_id' => 13],
        	['name' => 'Safe Custody','subcategory_id' => 13],
        	['name' => 'Change in Name and Address','subcategory_id' => 13],
        	['name' => 'Change in ownership','subcategory_id' => 13],
        	['name' => 'Change in Load/Demand','subcategory_id' => 13],
        	['name' => 'Change in Category','subcategory_id' => 13],
        	['name' => 'Fees and Security Deposite','subcategory_id' => 13],
        	['name' => 'Know Tariff','subcategory_id' => 13],
        	['name' => 'FAQs','subcategory_id' => 13],
        	['name' => 'Service Request','subcategory_id' => 13],
        	['name' => 'Test Your Meter','subcategory_id' => 14],
        	['name' => 'Purchase/Replace Meter','subcategory_id' => 14],
        	['name' => 'Shift Meter','subcategory_id' => 14],
        	['name' => 'Report stolen Meter','subcategory_id' => 14],
        	['name' => 'Report Defect/Damage Meter','subcategory_id' => 14],
        	['name' => 'Know your Meter','subcategory_id' => 14],
        	['name' => 'FAQs','subcategory_id' => 14],
        	['name' => 'Service Request','subcategory_id' => 14],
        	['name' => 'My Reading Date','subcategory_id' => 15],
        	['name' => 'My Consumption Pattern','subcategory_id' => 15],
        	['name' => 'Report your Reading(Incase not Read)','subcategory_id' => 15],
        	['name' => 'Get a copy downloaded data from meter','subcategory_id' => 15],
        	['name' => 'Report a wrong Reading','subcategory_id' => 15],
        	['name' => 'FAQs','subcategory_id' => 15],
        	['name' => 'Service Request','subcategory_id' => 15],
        	['name' => 'Report non Billing','subcategory_id' => 16],
        	['name' => 'Request Bill correction','subcategory_id' => 16],
        	['name' => 'Request Duplicate bill','subcategory_id' => 16],
        	['name' => 'Know your Bill Parameters','subcategory_id' => 16],
        	['name' => 'Understanding your bill','subcategory_id' => 16],
        	['name' => 'FAQs','subcategory_id' => 16],
        	['name' => 'Service Request','subcategory_id' => 16],
        	['name' => 'Pay bill Online','subcategory_id' => 17],
        	['name' => 'Modes of Payments','subcategory_id' => 17],
        	['name' => 'Payment Plans','subcategory_id' => 17],
        	['name' => 'Nearest Collection Cluster','subcategory_id' => 17],
        	['name' => 'Duplicate Money Receipt','subcategory_id' => 17],
        	['name' => 'Consequences of Non-Payments','subcategory_id' => 17],
        	['name' => 'FAQs','subcategory_id' => 17],
        	['name' => 'Service Request','subcategory_id' => 17],
        	['name' => 'No to Power Theft','subcategory_id' => 18],
        	['name' => 'Not to interfer with Power Installation','subcategory_id' => 18],
        	['name' => 'Inspection of Premises','subcategory_id' => 18],
        	['name' => 'FAQs','subcategory_id' => 18],
        	['name' => 'Service Request','subcategory_id' => 18],
        	['name' => 'Dos and Dont','subcategory_id' => 19],
        	['name' => 'Employees safety Practices','subcategory_id' => 19],
        	['name' => 'Get your Installation Certified','subcategory_id' => 19],
        	['name' => 'Invite us for testing','subcategory_id' => 19],
        	['name' => 'Grid Safety Practices','subcategory_id' => 19],
        	['name' => 'Our People at Work','subcategory_id' => 19],
        	['name' => 'FAQs','subcategory_id' => 19],
        	['name' => 'Service Request','subcategory_id' => 19],
        	['name' => 'Free Energy Audit','subcategory_id' => 20],
        	['name' => 'Plan your Device','subcategory_id' => 20],
        	['name' => 'Energy Efficiency','subcategory_id' => 20],
        	['name' => 'Plan your Consumption','subcategory_id' => 20],
        	['name' => 'Reduce power wastage','subcategory_id' => 20],
        	['name' => 'High Efficiency Equipment','subcategory_id' => 20],
        	['name' => 'Avoid Power factor penality','subcategory_id' => 20],
        	['name' => 'Own your capacity Bank','subcategory_id' => 20],
        	['name' => 'FAQs','subcategory_id' => 20],
        	['name' => 'Service Request','subcategory_id' => 20],
        	['name' => 'Register Yourself','subcategory_id' => 21],
        	['name' => 'FAQs','subcategory_id' => 21],
        	['name' => 'Raise a Service Request','subcategory_id' => 21],
        	['name' => 'Report outage','subcategory_id' => 21],
        	['name' => 'Report power theft/malpractice','subcategory_id' => 21],
        	['name' => 'Request for training','subcategory_id' => 21],
        	['name' => 'Load Calculator','subcategory_id' => 21],
        	['name' => 'Download Forms','subcategory_id' => 21],
        	['name' => 'Your Rights & Responsibilities','subcategory_id' => 21],
        	['name' => 'Feedback','subcategory_id' => 21],
        	['name' => 'Contact Us','subcategory_id' => 21],
        	['name' => 'Supply','subcategory_id' => 22],
        	['name' => 'Connection','subcategory_id' => 22],
        	['name' => 'Meter','subcategory_id' => 22],
        	['name' => 'Reading','subcategory_id' => 22],
        	['name' => 'Bill','subcategory_id' => 22],
        	['name' => 'Payment','subcategory_id' => 22],
        	['name' => 'Messages','subcategory_id' => 22],
        	['name' => 'Service Request','subcategory_id' => 22],
        	['name' => 'Compliances','subcategory_id' => 22],
        	['name' => 'Document Vault/Locker','subcategory_id' => 22],

        	['name' => 'Business Area','subcategory_id' => 23],
        	['name' => 'Grids','subcategory_id' => 23],
        	['name' => '33/11KV Substation','subcategory_id' => 23],
        	['name' => 'Feeder','subcategory_id' => 23],
        	['name' => 'DTs','subcategory_id' => 23],
        	['name' => 'Lines/Poles','subcategory_id' => 23],
        	['name' => 'Schedule Outage Policy','subcategory_id' => 23],
        	['name' => 'Unscheduled Outages','subcategory_id' => 23],
        	['name' => 'Forthcoming Augmentations','subcategory_id' => 23],

        	['name' => 'Equality of Service our pledge','subcategory_id' => 24],
        	['name' => 'Economic Environment','subcategory_id' => 24],
        	['name' => 'Our Job Creation efforts','subcategory_id' => 24],
        	['name' => 'CSR Activites','subcategory_id' => 24],
        	['name' => 'Natural Environment','subcategory_id' => 24],
        	['name' => 'Paperless Billing','subcategory_id' => 24],
        	['name' => 'Stop Electrifying Trees','subcategory_id' => 24],
        	['name' => 'Reduce Peak Consumption','subcategory_id' => 24],
        	['name' => 'Reduce Your Load','subcategory_id' => 24],
        	['name' => 'Reduce Your Power Leakage','subcategory_id' => 24],
        	['name' => 'Request Free Energy Audit','subcategory_id' => 24],
        	['name' => 'Employee Health','subcategory_id' => 24],
        	['name' => 'Community Health','subcategory_id' => 24],
        	['name' => 'Principle of Safety','subcategory_id' => 24],
        	['name' => 'People Safety','subcategory_id' => 24],
        	['name' => 'Grid Safety','subcategory_id' => 24],
        	['name' => 'Preventive Maintenance','subcategory_id' => 24],
        	['name' => 'Activity Schedule','subcategory_id' => 24],
        	['name' => 'Our People at Work','subcategory_id' => 24],

        	['name' => 'Consumers','subcategory_id' => 25],
        	['name' => 'Odisha Govt','subcategory_id' => 25],
        	['name' => 'CESU','subcategory_id' => 25],
        	['name' => 'OERC','subcategory_id' => 25],
        	['name' => 'Our Locations','subcategory_id' => 25],
        	['name' => 'Request For Training','subcategory_id' => 25],

        	['name' => 'Supply Associates','subcategory_id' => 26],
        	['name' => 'Service Associates','subcategory_id' => 26],
        	['name' => 'Meter Reading Associates','subcategory_id' => 26],
        	['name' => 'Bill Collection Associates','subcategory_id' => 26],
        	['name' => 'Enquiries/Tanders Associates','subcategory_id' => 26],

        	['name' => 'Working Environment','subcategory_id' => 27],
        	['name' => 'Training and Development','subcategory_id' => 27],
        	['name' => 'Current Vacancies','subcategory_id' => 27],
        	['name' => 'Submit Resume','subcategory_id' => 27],
        	['name' => 'Campus Recruitment','subcategory_id' => 27],

        	['name' => 'Mission/Vision/Values','subcategory_id' => 28],
        	['name' => 'Board of Directors','subcategory_id' => 28],
        	['name' => 'Business Leadership','subcategory_id' => 28],
        	['name' => 'Regional Leadership','subcategory_id' => 28],
        	['name' => 'Culture','subcategory_id' => 28],
        	['name' => 'Projects/Plans of Present future','subcategory_id' => 28],
        	['name' => 'Network Reliability','subcategory_id' => 28],
        	['name' => 'Service to door step','subcategory_id' => 28],

        	['name' => 'In news/current month','subcategory_id' => 29],
        	['name' => 'In News/Archive','subcategory_id' => 29],
        	['name' => 'Logos','subcategory_id' => 29],
        	['name' => 'other Downloads','subcategory_id' => 29],
        	['name' => 'Quick Facts','subcategory_id' => 29],
        	['name' => 'Public Relation','subcategory_id' => 29],

        	['name' => 'Electricity Act 2003','subcategory_id' => 30],
        	['name' => 'Electricity Rules','subcategory_id' => 30],
        	['name' => 'Supply Code 2007','subcategory_id' => 30],
        	['name' => 'Tariff Orders','subcategory_id' => 30],

        	['name' => 'Ethics Pledge','subcategory_id' => 31],
        	['name' => 'Ethics Code','subcategory_id' => 31],
        	['name' => 'Corruption Notice','subcategory_id' => 31],
        	['name' => 'Report a Corrupt Practice','subcategory_id' => 31],
        	['name' => 'Staffs No more Associated','subcategory_id' => 31],

        	['name' => 'Contact centre','subcategory_id' => 32],
        	['name' => 'Contact Through E-mail','subcategory_id' => 32],
        	['name' => 'Contact Through Letter','subcategory_id' => 32],
        	['name' => 'Contact Through Telephone','subcategory_id' => 32],
        	['name' => 'Meet Us at our Service Units','subcategory_id' => 32],
        	['name' => 'Send a Query','subcategory_id' => 32],
        	['name' => 'Do a Chat','subcategory_id' => 32],

        	['name' => 'Terms of Use','subcategory_id' => 33],

        	['name' => 'Privacy Statement','subcategory_id' => 34],

        	['name' => 'Cookies Policy','subcategory_id' => 35],

        	['name' => 'Site Map','subcategory_id' => 36],

        	['name' => 'Getting best of the website','subcategory_id' => 37]
    	);
        DB::table('pages')->insert(
        	$data
        );
    }
}
